require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'OdooShoppe' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  ) 

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.``
  # use_flipper!()

  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   # . . . // other subspecs
  #   'RCTLinkingIOS',
  #   # . . .
  # ]


  # pod 'FBSDKLoginKit'
    

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'

  post_install do |installer|
    react_native_post_install(installer)
  end
end