import {StyleSheet, Dimensions, Platform} from 'react-native';
import {Colors, Fonts} from '../utils/Constants';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {useTheme} from '../context/ThemeProvider';

// static {contextType} = useTheme();
// console.log('theme', contextType);

export default StyleSheet.create({
  Background: {
    backgroundColor: Colors.TRANSPARENT,
    height: Dimensions.get('window').height,
  },
  Wrap: {
    paddingHorizontal: '2%',
  },
  HeaderBg: {
    zIndex: 99,
    backgroundColor: Colors.PRIMARY,
    shadowColor: Colors.ACCENT,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 4,
    // width: wp,
  },
  Body: {
    minHeight: '89%',
    paddingTop: 20,
    paddingBottom: Platform.isPad ? 80 : 50,
    backgroundColor: Colors.SECONDARY,
    // borderTopLeftRadius: 50,
    // borderTopRightRadius: 50,
  },
  LoaderWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  LoaderImage: {
    width: 100,
    height: 100,
    resizeMode: 'center',
  },
  ContentOutWrap: {
    marginTop: -80,
  },
  DefaultText: {
    fontFamily: Fonts.LIGHT,
    fontSize: 14,
    color: Colors.ACCENT,
  },
  LinkText: {
    fontFamily: Fonts.REGULAR,
    fontSize: 14,
    color: Colors.LINK,
  },
  WhiteText: {
    fontFamily: Fonts.LIGHT,
    fontSize: 14,
    color: Colors.WHITE,
  },
  TouchableIcon: {
    textAlign: 'center',
  },
  Icon: {
    width: 25,
    height: 25,
    alignContent: 'center',
    justifyContent: 'center',
    resizeMode: 'contain',
  },
  SearchBarBg: {
    backgroundColor: Colors.WHITE,
    borderRadius: 5,
  },
  SearchBarInput: {
    flex: 1,
    fontFamily: Fonts.LIGHT,
    fontSize: 16,
    paddingHorizontal: 15,
    paddingVertical: Platform.isPad ? 10 : 4,
    color: Colors.ACCENT,
    backgroundColor: Colors.WHITE,
    borderRadius: 10,
    padding: 5
  },
  SearchBarTouchableText: {
    color: Colors.OVERLAY,
    fontFamily: Fonts.LIGHT,
    fontSize: 16,
    paddingVertical: 3,
  },
  Label: {
    fontFamily: Fonts.REGULAR,
    fontSize: 14,
    color: Colors.ACCENT,
    marginBottom: 10,
  },
  InputFieldLabel: {
    color: Colors.ACCENT,
    fontFamily: Fonts.REGULAR,
    marginBottom: 7,
  },
  InputFieldWrap: {
    paddingTop: 7,
    position: 'relative',
    backgroundColor: Colors.WHITE,
    borderRadius: 5,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: Colors.ACCENT_SECONDARY,
    // shadowColor: Colors.ACCENT,
    // shadowOffset: {
    //   width: 0,
    //   height: 3,
    // },
    // shadowOpacity: 0.27,
    // shadowRadius: 4.65,
    // elevation: 4,
  },
  InputFieldInput: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
    paddingTop: 4,
    paddingBottom: 11,
    paddingHorizontal: 10,
    color: Colors.ACCENT,
  },
  InputFieldTextareaWrap: {
    position: 'relative',
    backgroundColor: Colors.WHITE,
    borderRadius: 5,
    shadowColor: Colors.ACCENT,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 4,
  },
  InputFieldTextarea: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
    paddingVertical: 15,
    paddingHorizontal: 15,
    color: Colors.ACCENT,
    textAlignVertical: 'top',
  },
  PasswordEye: {
    position: 'absolute',
    bottom: 15,
    right: 0,
    zIndex: 999,
  },
  Card: {
    borderRadius: 15,
    padding: 15,
    backgroundColor: Colors.WHITE,
    shadowColor: Colors.ACCENT,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 4,
  },
  CategoryNoProductCard: {
    width: '90%',
    minHeight: 100,
    height: 'auto',
    paddingVertical: 20,
    marginBottom: 20,
    marginHorizontal: '5%',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Colors.ACCENT_SECONDARY,
    borderWidth: 1,
    borderRadius: 5,
    marginTop: 20,
  },
  CategoryNoProductText: {
    textAlign: 'center',
    fontFamily: Fonts.REGULAR,
    fontSize: 18,
    color: Colors.ACCENT_SECONDARY,
  },
  CategoryTab: {
    paddingRight: 20,
    paddingVertical: 10,
    marginRight: 25,
    borderBottomWidth: 2,
  },
  CategoryTabsList: {
    flexDirection: 'row',
    paddingLeft: '2%',
  },
  CategoryProductCardsList: {
    width: '96%',
    marginLeft: '2%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  CategoryProductCard: {
    width: '48%',
    marginTop: 5,
    marginBottom: 10,
    paddingVertical: 5,
    borderRadius: 5,
    backgroundColor: Colors.WHITE,
    borderStyle: 'solid',
    borderColor: Colors.ACCENT_SECONDARY,
    borderWidth: 1,
    padding: 10,
  },
  CategoryProductCardImage: {
    width: 'auto',
    height: 80,
    marginTop: 5,
    resizeMode: 'contain',
  },
  CategoryProductCardTitle: {
    marginTop: 10,
    fontSize: 14,
    fontFamily: Fonts.REGULAR,
  },
  CategoryProductCardPrice: {
    fontFamily: Fonts.REGULAR,
    marginTop: 5,
    marginBottom: 10,
    fontSize: 16,
    color: Colors.OVERLAY,
  },
  ButtonWrap: {
    borderRadius: 5,
    overflow: 'hidden',
  },
  Button: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    textTransform: 'uppercase',
    fontFamily: Fonts.REGULAR,
    fontSize: 11,
    color: Colors.WHITE,
    backgroundColor: Colors.PRIMARY,
  },
  BigButton: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    textTransform: 'uppercase',
    fontFamily: Fonts.REGULAR,
    color: Colors.WHITE,
    borderRadius: 5,
    backgroundColor: Colors.PRIMARY,
    fontSize: 20,
    paddingVertical: 10,
  },
  FullWidthButton: {
    alignSelf: 'stretch',
    paddingHorizontal: 10,
    textTransform: 'uppercase',
    fontFamily: Fonts.REGULAR,
    color: Colors.WHITE,
    borderRadius: 5,
    backgroundColor: Colors.PRIMARY,
    textAlign: 'center',
    fontSize: 18,
    paddingVertical: 12,
  },
  IconButton: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'center',
    alignContent: 'center',
    paddingVertical: 7,
    paddingHorizontal: 10,
    color: Colors.WHITE,
    borderRadius: 5,
    backgroundColor: Colors.PRIMARY,
  },
  IconButtonIcon: {
    width: 18,
    height: 18,
  },
  IconButtonText: {
    color: Colors.WHITE,
    textTransform: 'uppercase',
    fontFamily: Fonts.REGULAR,
  },
  IconButtonTextIcon: {
    marginRight: 7,
  },
  ProductsListItemCard: {
    flexDirection: 'row',
    marginBottom: 15,
    borderRadius: 15,
  },
  ProductsListItemImageWrap: {
    flex: 1,
    paddingRight: 5,
  },
  ProductsListItemImage: {
    width: 60,
    height: 80,
    resizeMode: 'contain',
  },
  ProductsListItemBodyWrap: {
    flex: 3,
    paddingRight: 5,
  },
  ProductsListItemTitle: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
  },
  ProductsListItemPrice: {
    marginTop: 7,
    fontSize: 18,
  },
  ProductsListItemRegularPrice: {
    fontSize: 12,
    fontFamily: Fonts.LIGHT,
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
  },
  ProductRatingCount: {
    fontFamily: Fonts.REGULAR,
    fontSize: 12,
    color: Colors.OVERLAY,
    marginLeft: 10,
  },
  ProductsListItemRatingWrap: {
    width: 120,
    marginTop: 7,
  },
  ProductsListItemButtonsWrap: {
    flexDirection: 'row',
    marginTop: 15,
  },
  ProductsListItemButton: {
    marginRight: 15,
  },
  ProductsListItemButtonIcon: {
    color: Colors.PRIMARY,
  },
  WishlistProductsCardButtonIcon: {
    color: Colors.RED,
  },
  OptionsList: {
    marginTop: 20,
  },
  OptionsListTitle: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
    marginBottom: 10,
  },
  OptionsListItem: {
    width: 40,
    height: 40,
    borderRadius: 30,
    borderWidth: 2,
    marginRight: 10,
    textAlign: 'center',
    lineHeight: 40,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  OptionsListItemPill: {
    width: 'auto',
    height: 40,
    borderRadius: 30,
    borderWidth: 2,
    marginRight: 10,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  OptionsListItemPillCircle: {
    width: 15,
    height: 15,
    borderRadius: 30,
    marginRight: 7,
    borderWidth: 2,
  },
  QuantityOption: {
    marginTop: 20,
  },
  QuantityOptionWrap: {
    width: 120,
    height: 45,
    borderRadius: 30,
    borderWidth: 2,
    marginRight: 10,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Colors.ACCENT_SECONDARY,
    backgroundColor: Colors.WHITE,
  },
  QuantityOptionText: {
    width: '70%',
    paddingHorizontal: 10,
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
    textAlign: 'center',
  },
  ProductDescriptionStyle: {
    backgroundColor: 'transparent',
  },
  BottomBar: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
    paddingVertical: 20,
    paddingHorizontal: '5%',
    zIndex: 99,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: Colors.WHITE,
    shadowColor: Colors.ACCENT,
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 4,
  },
  CartProductsListItemCard: {
    marginBottom: 15,
    // borderRadius: 15,
    backgroundColor: Colors.WHITE,
    paddingVertical: 15,
    paddingHorizontal: '3%',
  },
  CartProductsListItemTopRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingBottom: 10,
    marginBottom: 10,
    borderBottomColor: Colors.ACCENT_SECONDARY,
    borderBottomWidth: 1,
  },
  CartProductsListItemRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  CartProductsListItemImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    marginRight: 20,
  },
  CartQuantityOptionWrap: {
    width: 100,
    height: 35,
    borderRadius: 10,
    borderWidth: 2,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Colors.ACCENT_SECONDARY,
  },
  CartQuantityOptionIcon: {
    fontSize: 14,
  },
  CartProductsListItemRowTitle: {
    fontFamily: Fonts.REGULAR,
  },
  RadioOptionsWrap: {
    width: 'auto',
    borderBottomColor: Colors.ACCENT_SECONDARY,
    flexDirection: 'row',
    paddingVertical: 15,
  },
  OrderPlacedProdutListQuantity: {
    fontFamily: Fonts.REGULAR,
    fontSize: 14,
  },
  CommentCard: {
    flexDirection: 'row',
    paddingVertical: 15,
    borderBottomColor: Colors.ACCENT_SECONDARY,
    borderBottomWidth: 1,
  },
  CommentAvatar: {
    width: 50,
    height: 50,
    marginRight: 10,
    borderRadius: 5,
    resizeMode: 'cover',
  },
  CommentTitle: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
  },
  CommentTime: {
    marginTop: 7,
    marginBottom: 3,
    fontFamily: Fonts.REGULAR,
    fontSize: 12,
    color: Colors.OVERLAY,
  },
  CommentDesc: {
    marginTop: 4,
  },
  RatingBarsTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
    marginBottom: 10,
  },
  RatingBarsTitle: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
  },
  ReviewAndRatingWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  RatingBoxWrap: {
    flex: 0.7,
    paddingRight: 15,
    marginRight: 20,
    alignItems: 'center',
    borderRightColor: Colors.ACCENT_SECONDARY,
    borderRightWidth: 1,
  },
  RatingBoxRate: {
    fontFamily: Fonts.BOLD,
    fontSize: 30,
    marginBottom: 15,
  },
  RatingBoxStars: {
    width: 120,
    marginBottom: 5,
  },
  RatingBarsWrap: {
    flex: 1,
  },
  RatingBarWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 7,
  },
  RatingBarRate: {
    fontSize: 12,
    fontFamily: Fonts.REGULAR,
    marginRight: 3,
  },
  RatingBarBg: {
    position: 'relative',
    width: 110,
    height: 7,
    marginLeft: 7,
    borderRadius: 7,
    backgroundColor: Colors.ACCENT_SECONDARY,
  },
  RatingBarFg: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: 7,
    borderRadius: 7,
    backgroundColor: Colors.SUCCESS,
  },
  ViewAllComments: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
    marginTop: 10,
  },
  ViewAllCommentsText: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
  },
  SpotlightBannerWrap: {
    marginVertical: 10,
    overflow: 'hidden',
    borderRadius: 3,
  },
  SpotlightBanner: {
    resizeMode: 'cover',
  },
  FeaturedBannerWrap: {
    marginRight: 15,
    overflow: 'hidden',
    borderRadius: 5,
    shadowColor: Colors.ACCENT,
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 4,
  },
  FeaturedBanner: {
    marginBottom: 10,
    paddingVertical: 10,
    overflow: 'hidden',
    paddingLeft: '5%',
  },
  FetauredBannerCaption: {
    fontSize: 16,
    fontFamily: Fonts.REGULAR,
    textAlign: 'center',
    paddingHorizontal: '5%',
    marginTop: 10,
    marginBottom: 7,
  },
  FeaturedBannerImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  FeaturedBannerSlider: {
    marginTop: 10,
    marginBottom: 5,
  },
  FeaturedBannerSliderWrap: {
    width: Dimensions.get('window').width,
    marginTop: 10,
  },
  FeaturedBannerSliderSlide: {
    height: 'auto',
    marginBottom: 20,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: Colors.LIGHT_GREY,
  },
  FeaturedBannerSliderImage: {
    borderRadius: 5,
  },
  FourCards: {
    marginTop: 10,
    marginBottom: 15,
  },
  FourCardsCaption: {
    fontSize: 16,
    fontFamily: Fonts.REGULAR,
    marginTop: 10,
  },
  FourCardsExpiryWrap: {
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 15,
  },
  FourCardsExpiry: {
    fontSize: 12,
    fontFamily: Fonts.REGULAR,
    color: Colors.OVERLAY,
  },
  FourCardsCard: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    // justifyContent: 'space-around',
    alignItems: 'center',
    marginHorizontal: '5%',
  },
  FourCardItem: {
    paddingTop: 5,
    paddingBottom: 15,
    // paddingHorizontal: 18,
    width: Dimensions.get('window').width * 0.41,
    borderTopColor: Colors.ACCENT_SECONDARY,
    borderTopWidth: 1,
    borderRightColor: Colors.ACCENT_SECONDARY,
    borderRightWidth: 1,
  },
  FourCardsItemImage: {
    width: 'auto',
    height: 150,
    resizeMode: 'contain',
  },
  FourCardsItemTitle: {
    fontSize: 12,
    fontFamily: Fonts.REGULAR,
    textAlign: 'center',
  },
  FourCardsItemDescription: {
    fontSize: 12,
    textAlign: 'center',
    color: Colors.OVERLAY,
    marginTop: 7,
  },
  OrderTotalCard: {
    marginBottom: 15,
    backgroundColor: Colors.WHITE,
    paddingVertical: 15,
    paddingHorizontal: '3%',
  },
  OrderTotalCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.ACCENT_SECONDARY,
  },
  OrderTotalCardTitle: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
  },
  OrderTotalCardBody: {
    paddingVertical: 10,
  },
  OrderTotalCardTableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  OrderTotalCardFooter: {
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.ACCENT_SECONDARY,
  },
  OrderTotalCardFooterTitle: {
    fontFamily: Fonts.REGULAR,
  },
  OrderTotalCardPaddingBottom10: {
    paddingBottom: 10,
  },
  AddressCard: {
    marginBottom: 15,
    paddingHorizontal: '3%',
    paddingVertical: 10,
    backgroundColor: Colors.WHITE,
  },
  AddressCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.ACCENT_SECONDARY,
  },
  AddressCardTitle: {
    fontFamily: Fonts.REGULAR,
    fontSize: 16,
  },
  AddressCardBody: {
    paddingVertical: 10,
  },
  AddressCardBodyRow: {
    paddingBottom: 5,
  },
  AddressCardBodyNoAddress: {
    textAlign: 'center',
    marginTop: 10,
  },
  GoToWishlistIcon: {
    marginRight: 15,
  },
  GoToIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  IconBadgeWrap: {
    height: 20,
    marginLeft: 5,
    paddingHorizontal: 5,
    borderRadius: 5,
    backgroundColor: Colors.SECONDARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  IconBadge: {
    fontWeight: 'bold',
    color: Colors.PRIMARY,
  },
  ImageCarouselSlide: {
    width: Dimensions.get('window').width,
    padding: 0,
  },
  ImageCarouselWrap: {
    width: '100%',
    marginTop: 0,
    marginBottom: 0,
  },
  ImageCarouselImage: {
    resizeMode: 'cover',
    width: '100%',
  },
});
